//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HASAKI_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_HANG
    {
        public string MaBanHang { get; set; }
        public string MaKH { get; set; }
        public string MaSP { get; set; }
        public string MaHD { get; set; }
        public string MaNV { get; set; }
        public int SoLuongMua { get; set; }
        public decimal ChiPhi { get; set; }
        public decimal DoanhThu { get; set; }
        public decimal LoiNhuan { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
