//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HASAKI_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON()
        {
            this.BAN_HANG = new HashSet<BAN_HANG>();
            this.HOA_DON_CT = new HashSet<HOA_DON_CT>();
            this.PHIEU_DOI_TRA = new HashSet<PHIEU_DOI_TRA>();
        }
    
        public string MaHD { get; set; }
        public Nullable<System.DateTime> NgayTaoHD { get; set; }
        public decimal TriGia { get; set; }
        public decimal KhuyenMai { get; set; }
        public decimal TongTien { get; set; }
        public string GhiChu { get; set; }
        public string MaKH { get; set; }
        public string MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_HANG> BAN_HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON_CT> HOA_DON_CT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_DOI_TRA> PHIEU_DOI_TRA { get; set; }
    }
}
