//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HASAKI_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON_CT
    {
        public string MaHD { get; set; }
        public string MaSP { get; set; }
        public int SoLuongMua { get; set; }
        public decimal DonGia { get; set; }
        public decimal TongGia { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
    }
}
