//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HASAKI_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_DOI_TRA
    {
        public string MaPDT { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SoLuongDoi { get; set; }
        public decimal TongTien { get; set; }
        public string LyDoDoiTra { get; set; }
        public string YeuCauDoiTra { get; set; }
        public string MaNV { get; set; }
        public string MaHD { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
