//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HASAKI_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_XUAT_CT
    {
        public string MaXuat { get; set; }
        public string MaSP { get; set; }
        public string MaNV { get; set; }
        public string GhiChu { get; set; }
        public int SoLuongXuat { get; set; }
        public decimal DonGiaXuat { get; set; }
        public decimal TongXuat { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual PHIEU_XUAT PHIEU_XUAT { get; set; }
    }
}
