//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HASAKI_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_NHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_NHAP()
        {
            this.PHIEU_NHAP_CT = new HashSet<PHIEU_NHAP_CT>();
        }
    
        public string MaNhap { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public string NhaCungCap { get; set; }
        public decimal TongGiaTriNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_NHAP_CT> PHIEU_NHAP_CT { get; set; }
    }
}
